repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (autofix)
        args: ["--fix", "--exit-non-zero-on-fix"]
        stages: [pre-commit]
      - id: ruff
        name: ruff (check)
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests<2.32.0.20240521
        files: ^src/|^tests/
        stages: [pre-commit]

ci:
  autofix_prs: true
  autofix_commit_msg: "chore(pre-commit): auto-fixes from pre-commit hooks"









